/*
Apodeixis mailjet-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateNotificationAllOfRelationshipsDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationAllOfRelationshipsDestination{}

// CreateNotificationAllOfRelationshipsDestination struct for CreateNotificationAllOfRelationshipsDestination
type CreateNotificationAllOfRelationshipsDestination struct {
	Data DestinationKey `json:"data"`
}

type _CreateNotificationAllOfRelationshipsDestination CreateNotificationAllOfRelationshipsDestination

// NewCreateNotificationAllOfRelationshipsDestination instantiates a new CreateNotificationAllOfRelationshipsDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationAllOfRelationshipsDestination(data DestinationKey) *CreateNotificationAllOfRelationshipsDestination {
	this := CreateNotificationAllOfRelationshipsDestination{}
	this.Data = data
	return &this
}

// NewCreateNotificationAllOfRelationshipsDestinationWithDefaults instantiates a new CreateNotificationAllOfRelationshipsDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationAllOfRelationshipsDestinationWithDefaults() *CreateNotificationAllOfRelationshipsDestination {
	this := CreateNotificationAllOfRelationshipsDestination{}
	return &this
}

// GetData returns the Data field value
func (o *CreateNotificationAllOfRelationshipsDestination) GetData() DestinationKey {
	if o == nil {
		var ret DestinationKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationAllOfRelationshipsDestination) GetDataOk() (*DestinationKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateNotificationAllOfRelationshipsDestination) SetData(v DestinationKey) {
	o.Data = v
}

func (o CreateNotificationAllOfRelationshipsDestination) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationAllOfRelationshipsDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateNotificationAllOfRelationshipsDestination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationAllOfRelationshipsDestination := _CreateNotificationAllOfRelationshipsDestination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationAllOfRelationshipsDestination)

	if err != nil {
		return err
	}

	*o = CreateNotificationAllOfRelationshipsDestination(varCreateNotificationAllOfRelationshipsDestination)

	return err
}

type NullableCreateNotificationAllOfRelationshipsDestination struct {
	value *CreateNotificationAllOfRelationshipsDestination
	isSet bool
}

func (v NullableCreateNotificationAllOfRelationshipsDestination) Get() *CreateNotificationAllOfRelationshipsDestination {
	return v.value
}

func (v *NullableCreateNotificationAllOfRelationshipsDestination) Set(val *CreateNotificationAllOfRelationshipsDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationAllOfRelationshipsDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationAllOfRelationshipsDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationAllOfRelationshipsDestination(val *CreateNotificationAllOfRelationshipsDestination) *NullableCreateNotificationAllOfRelationshipsDestination {
	return &NullableCreateNotificationAllOfRelationshipsDestination{value: val, isSet: true}
}

func (v NullableCreateNotificationAllOfRelationshipsDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationAllOfRelationshipsDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
